// This code was generated by `SqlHydra.Sqlite` -- v5.1.0.
namespace AvdStats.DbSchema

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(5, 1, 0)
    let ns = "AvdStats.DbSchema"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Intervals =
        { IntervalId: int64
          Kind: string
          StartTime: string
          EndTime: string
          DurationMs: int64
          ConnectReason: string
          ReportContribMs: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "IntervalId"; Value = box this.IntervalId; ProviderDbType = None }
                  { WriteColumn.Name = "Kind"; Value = box this.Kind; ProviderDbType = None }
                  { WriteColumn.Name = "StartTime"; Value = box this.StartTime; ProviderDbType = None }
                  { WriteColumn.Name = "EndTime"; Value = box this.EndTime; ProviderDbType = None }
                  { WriteColumn.Name = "DurationMs"; Value = box this.DurationMs; ProviderDbType = None }
                  { WriteColumn.Name = "ConnectReason"; Value = box this.ConnectReason; ProviderDbType = None }
                  { WriteColumn.Name = "ReportContribMs"; Value = box this.ReportContribMs; ProviderDbType = None } ]

    let Intervals = table<Intervals>

    [<CLIMutable>]
    type RawEvents =
        { RecordId: int64
          Channel: string
          EventId: int64
          TimeCreated: string
          Provider: string
          Message: Option<string>
          PropertiesJson: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "RecordId"; Value = box this.RecordId; ProviderDbType = None }
                  { WriteColumn.Name = "Channel"; Value = box this.Channel; ProviderDbType = None }
                  { WriteColumn.Name = "EventId"; Value = box this.EventId; ProviderDbType = None }
                  { WriteColumn.Name = "TimeCreated"; Value = box this.TimeCreated; ProviderDbType = None }
                  { WriteColumn.Name = "Provider"; Value = box this.Provider; ProviderDbType = None }
                  { WriteColumn.Name = "Message"; Value = box this.Message; ProviderDbType = None }
                  { WriteColumn.Name = "PropertiesJson"; Value = box this.PropertiesJson; ProviderDbType = None } ]

    let RawEvents = table<RawEvents>

    [<CLIMutable>]
    type ServiceMeta =
        { MetaKey: string
          MetaValue: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "MetaKey"; Value = box this.MetaKey; ProviderDbType = None }
                  { WriteColumn.Name = "MetaValue"; Value = box this.MetaValue; ProviderDbType = None } ]

    let ServiceMeta = table<ServiceMeta>

    [<CLIMutable>]
    type StateSnapshots =
        { SnapshotId: int64
          CurrentKind: Option<string>
          CurrentStart: Option<string>
          Locked: int64
          ShadowKind: Option<string>
          ShadowStart: Option<string>
          Reason: Option<string> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "SnapshotId"; Value = box this.SnapshotId; ProviderDbType = None }
                  { WriteColumn.Name = "CurrentKind"; Value = box this.CurrentKind; ProviderDbType = None }
                  { WriteColumn.Name = "CurrentStart"; Value = box this.CurrentStart; ProviderDbType = None }
                  { WriteColumn.Name = "Locked"; Value = box this.Locked; ProviderDbType = None }
                  { WriteColumn.Name = "ShadowKind"; Value = box this.ShadowKind; ProviderDbType = None }
                  { WriteColumn.Name = "ShadowStart"; Value = box this.ShadowStart; ProviderDbType = None }
                  { WriteColumn.Name = "Reason"; Value = box this.Reason; ProviderDbType = None } ]

    let StateSnapshots = table<StateSnapshots>

    [<CLIMutable>]
    type SyncWatermarks =
        { Channel: Option<string>
          LastSyncedTime: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "Channel"; Value = box this.Channel; ProviderDbType = None }
                  { WriteColumn.Name = "LastSyncedTime"; Value = box this.LastSyncedTime; ProviderDbType = None } ]

    let SyncWatermarks = table<SyncWatermarks>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext; OpenContextAsync = openContextAsync }
